if(EXISTS "/home/picasothedealer/Documents/Projects/AegisPQC/build-bench/aegis_tests-b12d07c_tests.cmake")
  include("/home/picasothedealer/Documents/Projects/AegisPQC/build-bench/aegis_tests-b12d07c_tests.cmake")
else()
  add_test(aegis_tests_NOT_BUILT-b12d07c aegis_tests_NOT_BUILT-b12d07c)
endif()
